config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'

  resources :cocktails do
    resources :doses, only: %i[new create edit update]
    resources :reviews, only: %i[new create edit update]
  end

  resources :doses, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy, inverse_of: :cocktail
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  accepts_nested_attributes_for :doses, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name
  validates_uniqueness_of :name

  def self.search_by_name(query)
    return all unless query

    where("name ILIKE '%#{query}%'")
  end

  def add_or_create_dose(ingredient_name, dose_description)
    ingredient = Ingredient.find_by_name(ingredient_name) || Ingredient.create!(name: ingredient_name)

    self.doses.create!(description: dose_description, ingredient: ingredient)
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates_presence_of :description
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update destroy]

  def index
    @query = params.dig(:search, :name)
    @cocktails = Cocktail.search_by_name(@query).order(:name)
  end

  def show
    @reviews = Review.all
    @review = Review.new
    @review.cocktail = @cocktail
  end

  def new
    @cocktail = Cocktail.new
    @cocktail.doses.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy

    redirect_to root_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(
      :name, :image_url, :instructions, :photo,
      doses_attributes: %i[id description ingredient_id _destroy]
    )
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[edit update destroy]
  before_action :set_cocktail, only: %i[create edit update]

  def create
    @review = Review.new(review_params)
    @review.cocktail = @cocktail

    @review.save

    redirect_to @cocktail
  end

  def edit
  end

  def update
    @review.update(review_params)

    if @review.save
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def destroy
    @review.destroy

    redirect_to @review.cocktail
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_cocktail.html.erb
<div>
  <%= link_to cocktail_path(cocktail), class: "card-link" do %>
    <% if cocktail.photo.present? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key %>')">
        <h3><%= cocktail.name %></h3>
      </div>
    <% else %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cocktail.image_url %>')">
        <h3><%= cocktail.name %></h3>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cocktails/_dose_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>
  <div class="form-group mb-0">
    <div class="form-row align-items-center">
      <div class="col">
        <%= form.association :ingredient, collection: Ingredient.all.order(:name), prompt: "Add an ingredient", input_html: { class: 'form-control select2' }, label: false %>
      </div>
      <div class="col">
        <%= form.input :description, placeholder: "Add a description", label: false %>
      </div>
      <%= link_to "#", data: { action: "nested-form#remove_association" } do %>
        <i class="fas fa-trash text-dark"></i>
      <% end %>
    </div>
  </div>

  <%= form.hidden_field :_destroy %>
<% end %>

app/views/cocktails/_form.html.erb
<%= simple_form_for cocktail do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <%= f.input :name %>
    <%= f.input :instructions %>
    <%= f.input :image_url %>
    <%= f.input :photo, as: :file %>
  </div>

  <h4>Ingredients</h4>
  <div data-controller="nested-form">
    <template data-nested-form-target="template">
      <%= f.simple_fields_for :doses, Dose.new, child_index: 'NEW_RECORD' do |dose| %>
        <%= render 'dose_fields', form: dose %>
      <% end %>
    </template>

    <%= f.simple_fields_for :doses do |dose| %>
      <%= render 'dose_fields', form: dose %>
    <% end %>

    <div class="mb-3" data-nested-form-target="links">
      <%= link_to "#", data: { action: "click->nested-form#add_association"} do %>
        <i class="fas fa-plus text-dark"></i>
      <% end %>
    </div>
  </div>

  <%= f.button :submit, class: "btn btn-outline-dark mt-3 w-25" %>
  <%= link_to "Back", :back, class: "btn btn-outline-dark mt-3 w-25" %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail: <%= @cocktail.name %></h1>
<%= render "form", cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<div class="jumbotron">
  <h1 class="display-5">Search for a cocktail</h1>
  <div class="search-form-control form-group">
    <%= simple_form_for :search, url: root_path, method: "GET" do |f| %>
      <%= f.input :name, placeholder: @query, label: false, input_html: { class: "form-control string required", id: "search-typed-text" } %>
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    <% end %>
  </div>
  <!-- <p id="search-typed-text"></p> -->
</div>

<h1>All Cocktails</h1>
<div class="cards">
  <%= render @cocktails %>
</div>

app/views/cocktails/new.html.erb
<h1>Create a new Cocktail</h1>
<%= render "form", cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<div class="card-product">
  <% if @cocktail.photo.present? %>
    <%= cl_image_tag @cocktail.photo.key %>
  <% else %>
    <%= image_tag @cocktail.image_url %>
  <% end %>
  <div class="card-product-infos flex-fill">
    <div class="row mb-2">
      <div class="col">
        <h1><%= @cocktail.name %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-8 pr-5">
        <h2>Instructions</h2>
        <p><%= @cocktail.instructions %></p>
        <%= link_to "Edit", edit_cocktail_path, class: "btn btn-outline-dark mt-3 w-25" %>
        <%= link_to "Destroy", cocktail_path, method: 'delete', data: { confirm: "Are you sure?" }, class: "btn btn-outline-dark mt-3 w-25" %>
      </div>
      <div class="col-4">
        <h2>Ingredients</h2>
        <table class="table table-sm table-borderless">
          <tbody>
            <% @cocktail.doses.each do |dose| %>
              <tr>
                <td><%= dose.ingredient.name %></td>
                <td><%= dose.description %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="card mt-3">
  <div class="row mb-2">
    <div class="col">
      <h2>Reviews</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <table class="table table-sm table-borderless">
        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td style="max-width: 18px;">
                <% review.rating.times do %>
                  <i class="fas fa-star" style="margin: -2px;"></i>
                <% end %>
                <% (5 - review.rating).times do %>
                  <i class="far fa-star" style="margin: -2px;"></i>
                <% end %>
              </td>
              <td><%= review.content %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4">
      <%= render './reviews/form', cocktail: @cocktail, review: @review %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mister Lee's Cocktails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'liquor.svg' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container my-3 py-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<h4>Leave a Review</h4>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn btn-outline-dark" %>
<% end %>

app/views/reviews/edit.html.erb
<%= render 'form', cocktail: @cocktail, review: @review %>